### ISSUE TITLE
Missing Object Exception related to History view

### ISSUE THREAD

**Issue by bogdandr14** [oxygenxml/oxygen-git-plugin#106]
10:00:15.977 [AWT-EventQueue-0] ERROR com.oxygenxml.git.service.RevCommitUtil - org.eclipse.jgit.errors.MissingObjectException: Missing unknown bb9ca6ae7a285c7a1cbbaaf70439e8781cd39b33
org.eclipse.jgit.errors.MissingObjectException: Missing unknown bb9ca6ae7a285c7a1cbbaaf70439e8781cd39b33
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:135) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:203) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:908) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:818) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
	at com.oxygenxml.git.service.RevCommitUtil.getChangedFiles(RevCommitUtil.java:79) [classes/:?]
	at com.oxygenxml.git.view.historycomponents.RowHistoryTableSelectionListener.setCommitDescription(RowHistoryTableSelectionListener.java:145) [classes/:?]
	at com.oxygenxml.git.view.historycomponents.RowHistoryTableSelectionListener.access$0(RowHistoryTableSelectionListener.java:104) [classes/:?]
	at com.oxygenxml.git.view.historycomponents.RowHistoryTableSelectionListener$TableTimerListener.actionPerformed(RowHistoryTableSelectionListener.java:96) [classes/:?]
	at javax.swing.Timer.fireActionPerformed(Unknown Source) [?:1.8.0_202]
	at javax.swing.Timer$DoPostEvent.run(Unknown Source) [?:1.8.0_202]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_202]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_202]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_202]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_202]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_202]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_202]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_202]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_202]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_202]

**Comment by AlexJitianu** [comment]
It might happen when you present history and you change the repository. The event triggers a history refresh which overlaps with the table's selection change timer.

**Comment by AlexJitianu** [comment]
Another one from a similar situation, I suspect:
```
Exception in thread "AWT-EventQueue-0" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(Unknown Source)
    at com.oxygenxml.git.service.GitAccess.getBranchMap(GitAccess.java:2306)
    at com.oxygenxml.git.view.historycomponents.CommitMessageTableRenderer.getTableCellRendererComponent(CommitMessageTableRenderer.java:137)
    at javax.swing.JTable.prepareRenderer(Unknown Source)
    at ro.sync.ui.application.ApplicationTable.prepareRenderer(Unknown Source)
    at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
    at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
    at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
    at ro.sync.ui.application.bb.paint(Unknown Source)
    at javax.swing.plaf.ComponentUI.update(Unknown Source)
    at javax.swing.JComponent.paintComponent(Unknown Source)
    at javax.swing.JComponent.paint(Unknown Source)
    at javax.swing.JComponent.paintToOffscreen(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
```
