### ISSUE TITLE
Undo/Redo support in the commit text area

### ISSUE THREAD

**Issue by AlexJitianu** [oxygenxml/Oxygen-Git-Plugin#15]
It wouyld help a lot to be able to Undo/Redo while writing in the commit area.

**Comment by AlexJitianu** [comment]
`javax.swing.text.BadLocationException: Invalid location
        at javax.swing.text.GapContent.getChars(Unknown Source)
        at javax.swing.text.GapContent.getString(Unknown Source)
        at javax.swing.text.AbstractDocument.getText(Unknown Source)
        at com.oxygenxml.git.view.CommitPanel$UndoManager.undoableEditHappened(CommitPanel.java:351)
        at javax.swing.text.AbstractDocument.fireUndoableEditUpdate(Unknown Source)
        at javax.swing.text.AbstractDocument.handleRemove(Unknown Source)
        at javax.swing.text.AbstractDocument.remove(Unknown Source)
        at javax.swing.text.DefaultEditorKit$DeleteNextCharAction.actionPerformed(Unknown Source)
        at javax.swing.SwingUtilities.notifyAction(Unknown Source)
        at javax.swing.JComponent.processKeyBinding(Unknown Source)
        at javax.swing.JComponent.processKeyBindings(Unknown Source)
        at javax.swing.JComponent.processKeyEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
        at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
        at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)`

**Comment by AlexJitianu** [comment]
If I delete the last word from the text the following exception appears:
`javax.swing.text.BadLocationException: Invalid location
        at javax.swing.text.GapContent.getChars(Unknown Source)
        at javax.swing.text.GapContent.getString(Unknown Source)
        at javax.swing.text.AbstractDocument.getText(Unknown Source)
        at com.oxygenxml.git.view.CommitPanel$UndoManager.undoableEditHappened(CommitPanel.java:351)
        at javax.swing.text.AbstractDocument.fireUndoableEditUpdate(Unknown Source)
        at javax.swing.text.AbstractDocument.handleRemove(Unknown Source)
        at javax.swing.text.AbstractDocument.remove(Unknown Source)
        at javax.swing.text.DefaultEditorKit$DeleteNextCharAction.actionPerformed(Unknown Source)`
