### ISSUE TITLE
NPE when launching oXygen

### ISSUE THREAD

**Issue by tofi86** [oxygenxml/Oxygen-Git-Plugin#16]
This exception is shown in a modal dialog when launching oXygen after plugin installation:

```
[ main ]  -  java.lang.NullPointerException
java.lang.NullPointerException
	at com.oxygenxml.git.utils.StagingPanelRefresh.checkForGitRepositoriesUpAndDownFrom(StagingPanelRefresh.java:76)
	at com.oxygenxml.git.utils.StagingPanelRefresh.execute(StagingPanelRefresh.java:48)
	at com.oxygenxml.git.utils.StagingPanelRefresh.call(StagingPanelRefresh.java:42)
	at com.oxygenxml.git.CustomWorkspaceAccessPluginExtension.applicationStarted(CustomWorkspaceAccessPluginExtension.java:42)
	at ro.sync.exml.MainFrame.pvm(Unknown Source)
	at ro.sync.exml.MainFrame.<init>(Unknown Source)
	at ro.sync.exml.MainFrame.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ro.sync.ui.application.ApplicationLauncher.d(Unknown Source)
	at ro.sync.ui.application.ApplicationLauncher.launch(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ro.sync.exml.Oxygen.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:67)
```

I'm running oXygen Editor 19 in `de_DE` locale on a Mac.

**Comment by tofi86** [comment]
The "Git Staging View" is shown, but no buttons are visible.

**Comment by tofi86** [comment]
Thanks for the quick fix! 👍
