### ISSUE TITLE
ArrayIndexOutOfBoundsException when "Save All"

### ISSUE THREAD

**Issue by AdrianSorop** [oxygenxml/oxygen-git-plugin#46]
Crashes when saving all files

~~~~java.lang.ArrayIndexOutOfBoundsException: 0 &gt;= 0
java.lang.ArrayIndexOutOfBoundsException: 0 &gt;= 0
	at java.util.Vector.removeElementAt(Unknown Source)
	at javax.swing.tree.DefaultMutableTreeNode.remove(Unknown Source)
	at javax.swing.tree.DefaultMutableTreeNode.remove(Unknown Source)
	at com.oxygenxml.git.view.StagingResourcesTreeModel.deleteNodes(StagingResourcesTreeModel.java:107)
	at com.oxygenxml.git.view.StagingResourcesTreeModel.setFilesStatus(StagingResourcesTreeModel.java:209)
	at com.oxygenxml.git.view.ChangesPanel.createTreeView(ChangesPanel.java:180)
	at com.oxygenxml.git.view.StagingPanel$1$1.editorSaved(StagingPanel.java:198)
	at ro.sync.exml.workspace.b.e.d$2.editorSaved(Unknown Source)
	at ro.sync.exml.editor.tc.gsk(Unknown Source)
	at ro.sync.exml.editor.tc.saveDocument(Unknown Source)
	at ro.sync.exml.editor.vd.hcl(Unknown Source)~~~~

**Comment by sorincarbunaru** [comment]
Cannot reproduce.
