### ISSUE TITLE
NPE when comparing files in staging view 

### ISSUE THREAD

**Issue by AdrianSorop** [oxygenxml/Oxygen-Git-Plugin#47]
~~~~

java.lang.NullPointerException
    at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache$Table.index(UnpackedObjectCache.java:146)
    at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache$Table.contains(UnpackedObjectCache.java:109)
    at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache.isUnpacked(UnpackedObjectCache.java:64)
    at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:414)
    at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:159)
    at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:173)
    at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:144)
    at org.eclipse.jgit.lib.Repository.open(Repository.java:307)
    at com.oxygenxml.git.service.GitAccess.getInputStream(GitAccess.java:882)
    at com.oxygenxml.git.protocol.GitRevisionURLHandler$GitRevisionConnection.getInputStream(GitRevisionURLHandler.java:143)
~~~~

**Comment by AdrianSorop** [comment]
See https://docs.oracle.com/javase/7/docs/api/java/net/URLConnection.html#getInputStream()
