### ISSUE TITLE
While connection to the given add-on address given in the step 3:

### ISSUE THREAD

**Issue by chrisjohn727** [oxygenxml/oxygen-git-plugin#78]

**Comment by chrisjohn727** [comment]
ro.sync.net.protocol.https.HttpsException: There was a problem establishing the secure HTTPS connection. In case the server you are trying to connect to uses self-signed certificates, read the 'Troubleshooting HTTPS' section from the user manual.
 Full error message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at ro.sync.net.protocol.http.b.e.bb(Unknown Source)
	at ro.sync.net.protocol.http.b.e.h(Unknown Source)
	at ro.sync.net.protocol.http.abstraction.n.p(Unknown Source)
	at ro.sync.net.protocol.http.abstraction.n.d(Unknown Source)
	at ro.sync.net.protocol.http.WebdavHttpURLConnection.g(Unknown Source)
	at ro.sync.net.protocol.http.WebdavHttpURLConnection.getInputStream(Unknown Source)
	at ro.sync.net.protocol.http.WebdavHttpURLConnection.s(Unknown Source)
	at ro.sync.net.protocol.http.WebdavHttpURLConnection.getHeaderField(Unknown Source)
	at java.net.URLConnection.getHeaderFieldLong(Unknown Source)
	at java.net.URLConnection.getContentLengthLong(Unknown Source)
	at java.net.URLConnection.getContentLength(Unknown Source)
	at ro.sync.exml.addons.ExtensionsSynchronizer.c(Unknown Source)
	at ro.sync.exml.addons.ExtensionsSynchronizer.downloadAddonsInformation(Unknown Source)
	at ro.sync.exml.addons.c.b.f.qgk(Unknown Source)
	at ro.sync.exml.addons.c.b.f.igk(Unknown Source)
	at ro.sync.exml.addons.c.b.f$1.dxd(Unknown Source)
	at ro.sync.ui.application.mb.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	... 16 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 35 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	... 41 more

**Comment by sorincarbunaru** [comment]
Hello,

This is very weird... I don't know what to say. The certificates for https://raw.githubusercontent.com/ seem to be good.

What you could do if you want to install the Git plugin using the add-on mechanism is to select the "Automatically accept a security certificate, even if invalid" option from HTTP(S)/WebDAV Preferences (see https://www.oxygenxml.com/doc/versions/21.1/ug-editor/topics/https-webdav-preferences.html)

Another option is to try the offline installation mentioned in the README.

Best wishes,
Sorin Carbunaru
oXygen XML

**Comment by sorincarbunaru** [comment]
If this happens again, we can reopen the issue.
