### ISSUE TITLE
Handle org.eclipse.jgit.errors.LockFailedException and other Pull/Push generated exceptions

### ISSUE THREAD

**Issue by AlexJitianu** [oxygenxml/oxygen-git-plugin#99]
We  currently intercept errors generated by an existing lock file when the user persorms a Pull. This lock file usually remains when a git process crashed. We had an user report and it looks like JGit is now throwing exceptions when this happens. The exception is caught in {{com.oxygenxml.git.view.event.PushPullController.ExecuteCommandRunnable.executeCommand()}} and just logged (Attention, all git exceptions are {{java.lang.RuntimeException}}). 

I suggest handling the exception better in {{com.oxygenxml.git.view.event.PushPullController.ExecuteCommandRunnable.executeCommand()}}:
- check to see if it's a {{org.eclipse.jgit.errors.LockFailedException}} and present the same message that is currenly presented in {{com.oxygenxml.git.service.GitAccess.pull(String, String, PullType)}}
- If it's another exception, present it to the user. A pull or push failed and was not handled. The user needs to see something.

```
17:46:38.706 [pool-2-thread-1] ERROR com.oxygenxml.git.utils.GitOperationScheduler - java.util.concurrent.ExecutionException: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of reset command. Cannot lock C:\Users\swatib\Documents\DITA\dita-digital\.git\index. Ensure that no other process has an open file handle on the lock file C:\Users\swatib\Documents\DITA\dita-digital\.git\index.lock, then you may delete the lock file and retry.
java.util.concurrent.ExecutionException: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of reset command. Cannot lock C:\Users\swatib\Documents\DITA\dita-digital\.git\index. Ensure that no other process has an open file handle on the lock file C:\Users\swatib\Documents\DITA\dita-digital\.git\index.lock, then you may delete the lock file and retry.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at com.oxygenxml.git.utils.GitOperationScheduler$1.afterExecute(GitOperationScheduler.java:32) [git.support-2.2.0.jar:?]
...
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of reset command. Cannot lock C:\Users\swatib\Documents\DITA\dita-digital\.git\index. Ensure that no other process has an open file handle on the lock file C:\Users\swatib\Documents\DITA\dita-digital\.git\index.lock, then you may delete the lock file and retry.
        at org.eclipse.jgit.api.ResetCommand.call(ResetCommand.java:209) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
        at com.oxygenxml.git.service.GitAccess.pull(GitAccess.java:1095) ~[git.support-2.2.0.jar:?]
...
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock C:\Users\swatib\Documents\DITA\dita-digital\.git\index. Ensure that no other process has an open file handle on the lock file C:\Users\swatib\Documents\DITA\dita-digital\.git\index.lock, then you may delete the lock file and retry.
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:218) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:289) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:255) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
        at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1269) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
        at org.eclipse.jgit.api.ResetCommand.resetIndex(ResetCommand.java:365) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
        at org.eclipse.jgit.api.ResetCommand.call(ResetCommand.java:185) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
        at com.oxygenxml.git.service.GitAccess.pull(GitAccess.java:1095) ~[git.support-2.2.0.jar:?]

```

**Comment by AlexJitianu** [comment]
Code review:
1. _PushPullController.ExecuteCommandRunnable.createLockFailureMessageIfNeeded()_ appears to be an identical copy of _GitAccess.createLockFailureMessageIfNeeded()_. It's not wise to duplicate code because it makes it difficult to maintain it. In the future you might fix something in one place and forget the other.
2. In _PushPullController.ExecuteCommandRunnable.executeCommand()_, when we catch the {{JGitInternalException}}, a pull or push is the action that failed. Trying to do another pull will result in the same  {{JGitInternalException}} being thrown. This code will fail:

```
          PullCommand pullCmd = gitAccess.getGit().pull().setCredentialsProvider(CredentialsProvider.getDefault());
          try {
            PullResult pullCommandResult = pullCmd.call();
```
You can either remove it, or try changing _createLockFailureMessageIfNeeded()_.

**Comment by AlexJitianu** [comment]
Let's try make a small test that asserts we are treating this exception and we present it to the user. Here is an example of a test that creates a repository and executes a pull with the controller: _com.oxygenxml.git.view.DiffPresenterTest.testRebasingFileDiff()_. Just create a file _index.lock_ inside the .git directory before executing the pull and the command will fail. We can catch it by adding a code like this in the test: 

```
    Mockito.doAnswer(new Answer<Void>() {
      @Override
      public Void answer(InvocationOnMock invocation) throws Throwable {
        errorMessages.add((String) invocation.getArguments()[0]);
        exceptions.add((Throwable) invocation.getArguments()[0]);
        
        return null;
      }
    }).when((StandalonePluginWorkspace) PluginWorkspaceProvider.getPluginWorkspace()).showErrorMessage(Mockito.any(), Mockito.any());
```
